"""create institution

Revision ID: 013109148d8f
Revises: 8923e1535aab
Create Date: 2025-11-12 02:10:55.756141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013109148d8f'
down_revision: Union[str, Sequence[str], None] = '8923e1535aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institution', 'institution_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('institution_user_id_key'), 'institution', type_='unique')
    op.drop_constraint(op.f('institution_user_id_fkey'), 'institution', type_='foreignkey')
    op.drop_column('institution', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('institution_user_id_fkey'), 'institution', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('institution_user_id_key'), 'institution', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('institution', 'institution_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
