"""added cascade

Revision ID: 037583b23161
Revises: cdba448e04a7
Create Date: 2026-01-17 11:30:34.966523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037583b23161'
down_revision: Union[str, Sequence[str], None] = 'cdba448e04a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentprofile', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentprofile', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
