"""pic2

Revision ID: 110f161ffe0e
Revises: a0cb88e71425
Create Date: 2025-11-12 02:58:12.000410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '110f161ffe0e'
down_revision: Union[str, Sequence[str], None] = 'a0cb88e71425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutionprofile', sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutionprofile', 'profile_picture')
    # ### end Alembic commands ###
