"""faculty name

Revision ID: a5cf8e6f0f7f
Revises: f6574481ae5c
Create Date: 2025-11-05 16:42:31.795598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5cf8e6f0f7f'
down_revision: Union[str, Sequence[str], None] = 'f6574481ae5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentprofile', sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentprofile', 'institution_name')
    # ### end Alembic commands ###
