"""addedd

Revision ID: c5dad1fc7395
Revises: 406dc2943c1f
Create Date: 2025-11-05 15:31:00.399576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5dad1fc7395'
down_revision: Union[str, Sequence[str], None] = '406dc2943c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verification_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
