"""create not unique

Revision ID: da91a529a161
Revises: 066b60164ad7
Create Date: 2025-11-18 08:07:00.765251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da91a529a161'
down_revision: Union[str, Sequence[str], None] = '066b60164ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('institutionprofile_institution_id_key'), 'institutionprofile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('institutionprofile_institution_id_key'), 'institutionprofile', ['institution_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
