"""create institution

Revision ID: ee89836e8186
Revises: 013109148d8f
Create Date: 2025-11-12 02:13:39.998411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee89836e8186'
down_revision: Union[str, Sequence[str], None] = '013109148d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('institution_profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'institution_profile_picture')
    # ### end Alembic commands ###
