"""faculty

Revision ID: f6574481ae5c
Revises: c5dad1fc7395
Create Date: 2025-11-05 15:58:23.946933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6574481ae5c'
down_revision: Union[str, Sequence[str], None] = 'c5dad1fc7395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentprofile', sa.Column('faculty', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('studentprofile_user_id_fkey'), 'studentprofile', type_='foreignkey')
    op.create_foreign_key(None, 'studentprofile', 'user', ['user_id'], ['id'])
    op.drop_column('studentprofile', 'falcuty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentprofile', sa.Column('falcuty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'studentprofile', type_='foreignkey')
    op.create_foreign_key(op.f('studentprofile_user_id_fkey'), 'studentprofile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('studentprofile', 'faculty')
    # ### end Alembic commands ###
